# Generated by Django 4.2.3 on 2023-07-29 07:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('whatsapp', models.CharField(max_length=15, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('module', models.TextField(choices=[('Mono - 540W', 'Mono - 540W'), ('Mono - 545W', 'Mono - 545W'), ('Poly - 330W', 'Poly - 330W'), ('Poly - 335W', 'Poly - 335W')], default='Choose Module...', max_length=20)),
                ('panel', multiselectfield.db.fields.MultiSelectField(choices=[('Rayzon', 'Rayzon'), ('Goldi', 'Goldi'), ('Waree', 'Waree'), ('Pahal', 'Pahal')], max_length=100)),
                ('inverter', multiselectfield.db.fields.MultiSelectField(choices=[('KSolare', 'KSolare'), ('Solaryaan', 'Solaryaan'), ('Solis', 'Solis'), ('Polycab', 'Polycab'), ('Sofar', 'Polycab'), ('Sungrow', 'Sungrow'), ('GrowWATT', 'GrowWATT')], max_length=100)),
            ],
        ),
    ]
