# Generated by Django 4.2.3 on 2023-07-29 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoteform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='revision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='revision_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
