# Generated by Django 4.2.3 on 2023-07-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteform', '0002_quotedetails_created_date_quotedetails_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedetails',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
