# Generated by Django 4.2.3 on 2023-08-01 11:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quoteform', '0003_quotedetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedetails',
            name='inverter',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('KSolare', 'KSolare'), ('Solaryaan', 'Solaryaan'), ('Solis', 'Solis'), ('Polycab', 'Polycab'), ('Sofar', 'Sofar'), ('Sungrow', 'Sungrow'), ('GrowWATT', 'GrowWATT')], max_length=100),
        ),
    ]
