# Generated by Django 4.2.3 on 2023-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteform', '0004_alter_quotedetails_inverter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedetails',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
