# Generated by Django 4.2.3 on 2023-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteform', '0005_quotedetails_email_quotedetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedetails',
            name='treesystem',
            field=models.TextField(choices=[('Solar Rooftop System', 'Solar Rooftop System'), ('Solar Gazebo System', 'Solar Gazebo System'), ('Solar Hybrid System', 'Solar Hybrid System')], default='Choose Tree System...', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='module',
            field=models.TextField(choices=[('Mono Bifacial - 330/335/340W', 'Mono Bifacial - 330/335/340W'), ('Mono Perc - 535/540/545W', 'Mono Perc - 535/540/545W'), ('Poly Crystalline - 535/540/545W', 'Poly Crystalline - 535/540/545W')], default='Choose Module...', max_length=50),
        ),
    ]
