# Generated by Django 4.2.3 on 2023-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteform', '0007_quotedetails_additional_quotedetails_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedetails',
            name='capacity',
            field=models.FloatField(null=True),
        ),
    ]
