# Generated by Django 4.2.3 on 2023-08-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteform', '0008_alter_quotedetails_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedetails',
            name='module',
            field=models.TextField(choices=[('Mono Bifacial - 535/540/545W', 'Mono Bifacial - 535/540/545W'), ('Mono Perc - 535/540/545W', 'Mono Perc - 535/540/545W'), ('Poly Crystalline - 330/335/340W', 'Poly Crystalline - 330/335/340W')], default='Choose Module...', max_length=50),
        ),
    ]
